#+title: Lean4-Mode - Changelog
#+language: en

* Version 1.1.2

- Fix occasional errors like "The connected server(s) does not support
  method =$/lean/plainGoal=" by not wrapping invocations of
  ~lsp-protocol~ macro into ~eval-when-compile~ but rather into
  ~eval-and-compile~.  Thus, the methods should now work, no matter
  whether Lean4-Mode was loaded by interpreting =.el= Elisp code or by
  loading compiled =.elc= or =.eln= files.  ([[https://github.com/leanprover-community/lean4-mode/issues/54][Bug#54]], [[https://leanprover.zulipchat.com/#narrow/channel/468104-Emacs/topic/lsp-mode.20errors.20due.20to.20list.20!.3D.20hash-table][Zulip discussion]])

* Version 1.1.1

- Assign all customizable user-options to the Lean4-Mode specific
  =lean4= group.  To customize Lean4-Mode, you now need to type =M-x
  customize-group RET lean4 RET=.

* Version 1.1.0

- To =lean4= customization group, add link to local info manual and
  use Lean4-Mode Github URL as website.
- Introduce new dependency on Elpa package =compat=.
- Remove dependency on Elpa package Flycheck.  It is still supported
  but not required.

* Version 1.0.1

- Specify Yury G. Kudryashov as maintainer.
- Rework README.  (Now in Org format).
- Provide README as Texi and Info manual too.

* Version 1.0

- Specify "Version" in Emacs-Lisp library header.
