#+title: Emacs Lean4-Mode
#+language: en
#+export_file_name: lean4-mode.texi
#+texinfo_dir_category: Emacs misc features
#+texinfo_dir_title: Lean4-Mode: (lean4-mode).
#+texinfo_dir_desc: Emacs major mode for Lean4 language

This package extends [[https://www.gnu.org/software/emacs/][GNU Emacs]] by a major mode for [[https://lean-lang.org][Lean]] version 4, a
programming language and theorem prover.

Lean4-Mode is developed on [[https://github.com/leanprover-community/lean4-mode][Github]].  Bugs and feature requests are also
tracked there.  Further discussions take place in the [[https://leanprover.zulipchat.com/#narrow/channel/468104-Emacs][#Emacs]] channel
on the Lean Zulip chat platform.

* Installation

** Brief, Generic Instructions

First, install the dependencies of Lean4-Mode:
- [[https://lean-lang.org/lean4/doc/setup.html][Lean]] (version 4)
- Emacs (version 27 or later)
- Emacs packages [[https://github.com/magnars/dash.el][Dash]] (available on GNU-Elpa), [[https://emacs-lsp.github.io/lsp-mode][lsp-mode]], and
  [[https://github.com/magit/magit/blob/main/lisp/magit-section.el][Magit-Section]] (available on Melpa)
Additionally, we'll assume you have Git installed.

Second, install Lean4-Mode itself:
- Clone the [[https://github.com/leanprover-community/lean4-mode][Git repository]].
- In your [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Init-File.html][Emacs initialization file]], add the path to your local
  repository to ~load-path~.

Third, ensure Lean4-Mode is loaded by one of the following ways:
- Load it eagerly.
- Load it lazily by associating ~lean4-mode~ with the =.lean= file
  extension and setting it up as autoloaded command.
- Load it lazily by generating an autoload file (with the Make target
  called =autoload=) and loading that in your init file. Make sure to
  regenerate the autoload file, whenever you change the Lean4-Mode
  repository (e.g. =git pull=).

** Detailed, Native Instructions

Install Lean version 4.

Install Emacs version 27 or later.

Install the Emacs packages Dash, lsp-mode and Magit-Section.  Dash is
the only one of these packages that is available in the default [[https://elpa.gnu.org][GNU
Elpa]] package-archive.  You can install the remaining packages either
from source or from [[https://melpa.org/#/getting-started][Melpa]] package-archive.  For later approach, add
the following to your Emacs initialization file
(e.g. =~/.emacs.d/init.el=):

#+begin_src elisp
(require 'package)

(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))

(add-to-list 'package-selected-packages 'dash)
(add-to-list 'package-selected-packages 'lsp-mode)
(add-to-list 'package-selected-packages 'magit-section)

(package-refresh-contents)
(package-install-selected-packages 'no-confirm)
#+end_src

Clone the Git repository of Lean4-Mode:

#+begin_src shell
git clone https://github.com/leanprover-community/lean4-mode.git ~/path/to/lean4-mode
#+end_src

In your Emacs initialization file, add the path to your local
Lean4-Mode repository to the ~load-path~ list:
#+begin_src elisp
(add-to-list 'load-path "~/path/to/lean4-mode")
#+end_src

Now you can choose one of the following ways to determine how
Lean4-Mode is loaded:

If you want Emacs to load Lean4-Mode eagerly whenever it is started,
put in your init file:
#+begin_src elisp
(require 'lean4-mode)
#+end_src

If you want Emacs to load Lean4-Mode lazily, i.e. when a Lean4 source
file is opened the first time, put in your init file:
#+begin_src elisp
(autoload 'lean4-mode "lean4-mode" nil t)
(add-to-list 'auto-mode-alist '("\\.lean\\'" . lean4-mode))
#+end_src

If you want Emacs to load Lean4-Mode lazily, you can also generate an
autoload file and load it in your init file. That is, whenever your
Git repository changes (e.g. =git pull=), run =make autoload=
inside. And put this in your init file:
#+begin_src elisp
(require 'lean4-mode-autoloads)
#+end_src

** Instructions for Source-Based Use-Package

This section instructs how to set up Lean4-Mode through the
~use-package~ macro that is built into Emacs since version 29.

If you use a source-based package-manager (e.g. =package-vc.el=,
Straight or Elpaca), then make sure to list the ="data"= directory in
your Lean4-Mode package recipe.

When customizing Lean4-Mode variables, make sure the customization
takes place after loading the Lean4-Mode package so that the variables
are correctly initialized first. For example, many Lean4-Mode hook
variables like ~lean4-mode-hook~ have non-nil initialization
values. And since ~use-package~ applies the =:hook= specifications
before package loading, you should avoid it. Instead, put
=(add-hook 'lean4-...-hook #'...)= under the =:config= section. (See
/Common Pitfalls/ section below.)

Use-Package [[https://www.gnu.org/software/emacs/manual/html_node/use-package/Deferring-loading.html][involves]] some complexity when it comes to deciding whether
to load a package eagerly (/demand/) or lazily (/defer/). For example,
it depends on your configuration (e.g. ~use-package-always-defer~,
~use-package-always-demand~). Assuming you want Lean4-Mode to be
invoked as major mode when opening a Lean source file, the simplest
solution would be eager loading, e.g. via =:demand t=. Alternatively,
you can defer loading e.g. via =:defer t= together with
=:mode "\\.lean\\'"= (which associates Lean4-Mode with the =.lean=
file extension) and =:commands lean4-mode= (which will set up
autoloading).

Following subsections show concrete examples.

*** Native =:vc= (Emacs 30 or later)

Since version 30, Emacs comes with a built-in =:vc= keyword for the
~use-package~ macro that utilizes =package-vc.el= to install Emacs
packages from remote source repositories.

#+begin_src elisp
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
(package-initialize)

(use-package lean4-mode
  :commands lean4-mode
  :mode "\\.lean\\'"
  :vc ( :url "https://github.com/leanprover-community/lean4-mode.git"
        :rev :last-release
        ;; Or, if you prefer the bleeding edge version of Lean4-Mode:
        ;; :rev :newest
        ))
#+end_src

*** Doom ~package!~

If you use Doom-Emacs, you can place the following code in your Doom
initialization file:

#+begin_src elisp
(package! lean4-mode
          :recipe ( :host github
                    :repo "leanprover-community/lean4-mode"
                    :files ("*.el" "data")))
#+end_src

*** Straight

If you use the Straight package manager through Use-Package, then
place the following code in your Emacs initialization file:

#+begin_src elisp
(use-package lean4-mode
  :commands lean4-mode
  :mode "\\.lean\\'"
  :straight (lean4-mode :type git :host github
                        :repo "leanprover-community/lean4-mode"
                        :files ("*.el" "data")))
#+end_src

* Usage

If things are working correctly, you should see the word "Lean4" in
Emacs mode-line when you open a file with =.lean= extension.  Emacs
will ask you to identify the /project/ this file belongs to.  If you
then type =#check id=, the word =#check= will be underlined, and
hovering over it will show you the type of ~id~.

To view the proof state, run ~lean4-info-mode~ (=C-c C-i=).  This
will display the =*Lean4 Info*= buffer (like the Lean Info-View pane
in VS-Code) in a separate window.

| Key                    | Description                                            | Command                     |
|------------------------+--------------------------------------------------------+-----------------------------|
| =C-c C-k=              | Echo the keystroke needed to input the symbol at point | ~quail-show-key~            |
| =C-c C-d=              | Recompile and reload imports                           | ~lean4-lsp-document-reopen~ |
| =C-c C-x= or =C-c C-l= | Execute Lean4 in stand-alone mode                      | ~lean4-execute~             |
| =C-c C-p C-l=          | Builds package with lake                               | ~lean4-lake-build~          |
| =C-c C-i=              | Toggle Info-View which shows goals and errors at point | ~lean4-info-mode~           |

** lsp-mode

For key bindings from lsp-mode, see [[https://emacs-lsp.github.io/lsp-mode/page/keybindings/][its respective documentation]] and
note that not all capabilities are supported by Lean4-Mode.

** Flycheck

You may optionally use Lean4-Mode together with Flycheck.  In that
case, the mode-line will show =FlyC:E/N=, indicating that there are
=E= number of errors and =N= number of notes.  Following keys will be
available by default (via ~flycheck-mode-map~):

| Key       | Description          | Command                   |
|-----------+----------------------+---------------------------|
| =C-c ! n= | Go to next error     | ~flycheck-next-error~     |
| =C-c ! p= | Go to previous error | ~flycheck-previous-error~ |

* Configuration

** lsp-mode

If you want breadcrumbs of namespaces and sections to be shown in the
header-line, set the user option ~lsp-headerline-breadcrumb-enable~ to
~t~.

** Flycheck

Flycheck is an optional but supported dependency of Lean4-Mode.  If
Flycheck is installed, lsp-mode and thus Lean4-Mode will by default
use it.  If you want to customize this behavior, e.g. if you'd like to
use Emacs' built-in Flymake package instead of Flycheck while keeping
later installed, then customize the ~lsp-diagnostics-provider~ user
option accordingly.

* Common Pitfalls

** Coexistence with Lean3-Mode

Lean4-Mode only supports version 4 of Lean.  For editing code written
in deprecated version 3, use [[https://github.com/leanprover/lean3-mode][Lean3-Mode]].  It is possible for both
packages to be installed in parallel and used independently.  But as a
user, it's your responsibility to set this up correctly.  You need to
take care of following issues in particular:

- Lean3-Mode uses =lean-= as prefix (e.g. for commands) whereas
  Lean4-Mode uses =lean4-= as prefix.  When Lean4-Mode is active,
  you must not use commands with prefix =lean-=.

- Both packages associate the =.lean= file extension with their
  respective commands.  Even more confusingly, they use different
  functions and regular expressions to do so.

  Lean3-Mode:
  #+begin_src elisp
  ;;;###autoload
  (push '("\\.lean$" . lean-mode) auto-mode-alist)
  #+end_src

  Lean4-Mode:
  #+begin_src elisp
  ;;;###autoload
  (add-to-list 'auto-mode-alist '("\\.lean\\'" . lean4-select-mode))
  #+end_src

  Make sure that both packages are loaded, autoloaded and configured
  in such a way ~auto-mode-alist~ ends up with your desired value.

- In particular, if you want Emacs to automatically detect whether
  Lean3- or Lean4-Mode should be used for a particular file or
  project, you'll need to define your own Elisp function and associate
  it with the Lean file extension. If desired, you can even do this
  directory locally (via the special "variable" =eval= in
  =.dir-locals.el=).

** Partial value of ~lean4-mode-hook~ or other hook variables

If you customize a hook variable like ~lean4-mode-hook~ e.g. with
~add-hook~ or Use-Package's =:hook= keyword, you may end up with a
partial / incomplete value of the hook variable. For example,
~lean4-mode-hook~ may not contain the ~lsp~ command and as a
consequence ~lsp-mode~ won't start automatically together with
Lean4-Mode.

There are several reasons that lead to this situation in conjunction:
(1.) Lean4-Mode has non-nil initialization values for many of its hook
variables. (2.) Emacs evaluates your ~add-hook~ form before it loads
the definition of the hook from Lean4-Mode package. (3.) ~add-hook~
effectively initializes the passed hook-variable to nil when the
symbol has no value cell. And (4.), Use-Package applies passed =:hook=
specifications before package loading.

If you do not use Use-Package, the solution is to load Lean4-Mode
before calling ~add-hook~, e.g. with ~require~:
#+begin_src elisp
(require 'lean4-mode)
(add-hook 'lean4-...-hook #'...)
#+end_src

Or with ~with-eval-after-load~:
#+begin_src elisp
(with-eval-after-load 'lean4-mode
  (add-hook 'lean4-mode-hook #'...))
(with-eval-after-load 'lean4-lsp
  (add-hook 'lean4-lsp-mode-hook #'...))
#+end_src

If you do Use-Package, you can solve the problem by calling ~add-hook~
within the =:config= section:
#+begin_src elisp
(use-package lean4-mode
  ;; ...
  :config
  (add-hook 'lean4-...-hook #'...))
#+end_src

* Changelog

** Upcoming Version

Documentation:
- The changelog is now part of the readme (and thus of the Info
  manual).

User interface:
- The tool-bar menu of Lean4-Mode does not list the
  ~flycheck-list-errors~ anymore. Please use the “Show all errors”
  entry in Flycheck's menu instead. (Fixes [[https://github.com/leanprover-community/lean4-mode/issues/91][#91]].)

Features:
- The variable ~lean4-delete-trailing-whitespace~ has been removed
  together with related code. Instead of reinventing the wheel,
  Lean4-Mode demands users to use Emacs' built-in facilities for this
  kind of use case. For example, you might want to define a function
  that buffer-locally adds ~delete-trailing-whitespace~ to
  ~before-save-hook~, and add that hereby defined function to
  ~lean4-mode-hook~.
- The variable ~lean4-autodetect-lean3~ has been removed along with
  the command ~lean4-select-mode~ and related code. If you still use
  legacy version 3 of Lean for some files or projects, you could
  directory- or file-locally associate the =.lean= file extension with
  Lean3-Mode in ~auto-mode-alist~.
- The command ~lean4-show-version~ has been removed. Lean4-Mode now
  assumes Lean version 4. In order to determine the minor version, you
  may type =M-! lean --version RET= or similar.
- The functions ~lean4-input-export-translations~ and
  ~lean4-input-export-translations-to-stdout~ have been removed. We
  expect that noone has been using it. If you do use it, let us know,
  so we can reconsider our decision in case of a substantial amount of
  users. Otherwise, please just define these functions in your Emacs
  initialization file yourself.
- The command ~lean4-std-exe~ has been removed. It was just the same
  as ~lean4-execute~ which continues to exist.

** Version 1.1.2 from 2024-12-10

- Fix occasional errors like "The connected server(s) does not support
  method =$/lean/plainGoal=" by not wrapping invocations of
  ~lsp-protocol~ macro into ~eval-when-compile~ but rather into
  ~eval-and-compile~.  Thus, the methods should now work, no matter
  whether Lean4-Mode was loaded by interpreting =.el= Elisp code or by
  loading compiled =.elc= or =.eln= files.  ([[https://github.com/leanprover-community/lean4-mode/issues/54][Bug#54]], [[https://leanprover.zulipchat.com/#narrow/channel/468104-Emacs/topic/lsp-mode.20errors.20due.20to.20list.20!.3D.20hash-table][Zulip discussion]])

** Version 1.1.1 from 2024-12-02

- Assign all customizable user-options to the Lean4-Mode specific
  =lean4= group.  To customize Lean4-Mode, you now need to type =M-x
  customize-group RET lean4 RET=.

** Version 1.1.0 from 2024-12-01

- To =lean4= customization group, add link to local info manual and
  use Lean4-Mode Github URL as website.
- Introduce new dependency on Elpa package =compat=.
- Remove dependency on Elpa package Flycheck.  It is still supported
  but not required.

** Version 1.0.1 from 2024-11-21

- Specify Yury G. Kudryashov as maintainer.
- Rework README.  (Now in Org format).
- Provide README as Texi and Info manual too.

** Version 1.0 from 2024-11-16

- Specify "Version" in Emacs-Lisp library header.

* Contributing

When you contribute to Lean4-Mode, add a personal copyright like
=;; Copyright (c) 2024 Firstname Lastname= to the header of respective
files.

You can use Emacs' built-in ~bug-reference-mode~ and
~bug-reference-prog-mode~ in this repository to make mentions of
issues like =#123= clickable.
