name: Lint
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Install Python (for melpazoid)
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install melpazoid
      run: |
        git clone --depth=1 https://github.com/riscy/melpazoid.git ~/melpazoid
        pip install ~/melpazoid

    - name: Install Emacs
      uses: purcell/setup-emacs@master
      with:
        version: snapshot

    - name: Run melpazoid
      run: make -C ~/melpazoid
      env:
        LOCAL_REPO: ${{ github.workspace }}
        RECIPE: '(lean4-mode :fetcher github :repo "leanprover/lean4-mode" :files (:defaults "data"))'
        EXIST_OK: true
